---
dependency:
  name: shell
  command: pip install python-nginx
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: alpine-3.8
    image: alpine:3.8
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
  - name: alpine-3.9
    image: alpine:3.9
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
  - name: alpine-3.10
    image: alpine:3.10
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
  - name: alpine-3.11
    image: alpine:3.11
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
provisioner:
  name: ansible
  playbooks:
    converge: ../common/playbook_template.yml
verifier:
  name: testinfra
  directory: ../common/test_template
