---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Set repo if Alpine
      ansible.builtin.set_fact:
        version: =1.21.6-r1
      when: ansible_facts['os_family'] == "Alpine"
    - name: Set repo if Debian
      ansible.builtin.set_fact:
        version: =1.21.6-1~{{ ansible_facts['distribution_release'] }}
      when: ansible_facts['os_family'] == "Debian"
    - name: Set repo if Red Hat
      ansible.builtin.set_fact:
        version: -1.21.6-1.{{ (ansible_facts['distribution'] == "Amazon") | ternary('amzn2', ('el' + ansible_facts['distribution_major_version'] | string)) }}.ngx
      when: ansible_facts['os_family'] == "RedHat"
    - name: Set repo if SLES
      ansible.builtin.set_fact:
        version: =1.21.6-1.sles{{ ansible_facts['distribution_major_version'] }}.ngx
      when: ansible_facts['os_family'] == "Suse"
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: ansible-role-nginx
      vars:
        nginx_version: "{{ version }}"
