---
- name: Prepare license
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create ephemeral license certificate file from b64 decoded env var # noqa template-instead-of-copy
      ansible.builtin.copy:
        content: "{{ lookup('env', 'NGINX_CRT') | b64decode }}"
        dest: ../../files/license/nginx-repo.crt
        force: false
        mode: 0444

    - name: Create ephemeral license key file from b64 decoded env var # noqa template-instead-of-copy
      ansible.builtin.copy:
        content: "{{ lookup('env', 'NGINX_KEY') | b64decode }}"
        dest: ../../files/license/nginx-repo.key
        force: false
        mode: 0444

- name: Prepare NGINX Plus
  hosts: all
  pre_tasks:
    - name: Set repo if Alpine
      ansible.builtin.set_fact:
        version: =26-r1
      when: ansible_facts['os_family'] == "Alpine"
    - name: Set repo if Debian
      ansible.builtin.set_fact:
        version: =26-1~{{ ansible_facts['distribution_release'] }}
      when: ansible_facts['os_family'] == "Debian"
    - name: Set repo if Red Hat
      ansible.builtin.set_fact:
        version: -26-1.{{ (ansible_facts['distribution'] == "Amazon") | ternary('amzn2', ('el' + ansible_facts['distribution_major_version'] | string)) }}.ngx
      when: ansible_facts['os_family'] == "RedHat"
    - name: Set repo if SLES
      ansible.builtin.set_fact:
        version: =26-1.sles{{ ansible_facts['distribution_major_version'] }}.ngx
      when: ansible_facts['os_family'] == "Suse"
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: ansible-role-nginx
      vars:
        nginx_type: plus
        nginx_license:
          certificate: license/nginx-repo.crt
          key: license/nginx-repo.key
        nginx_version: "{{ version }}"
