---
collections:
  - name: ansible.posix
    version: 1.6.0
  - name: community.general
    version: 9.5.0
  - name: community.crypto
    version: 2.22.1
  - name: community.docker
    version: 3.13.0
