---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 10.2.0
  - name: community.crypto
    version: 2.23.0
  - name: community.docker
    version: 4.3.0
