---
name: 🐛 Bug report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you continue filling out this report, please take a moment to check that your bug has not been [already reported on GitHub][issue search] 🙌

        Remember to redact any sensitive information such as authentication credentials and/or license keys!

        **Note:** If you are seeking community support or have a question, please consider starting a new thread via [GitHub discussions][discussions] or the [NGINX Community forum][forum].

        [issue search]: https://github.com/nginxinc/ansible-role-nginx/issues
        [discussions]: https://github.com/nginxinc/ansible-role-nginx/discussions
        [forum]: https://community.nginx.org

  - type: textarea
    id: overview
    attributes:
      label: Bug Overview
      description: A clear and concise overview of the bug.
      placeholder: When I do "X" with the NGINX Ansible role, "Y" happens instead of "Z".
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: When I do "X" with the NGINX Ansible role, I expect "Z" to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug
      description: Detail the series of steps required to reproduce the bug.
      value: |
        1. I have deployed/run the NGINX Ansible role using the following `playbook.yml`...
        2. I have seen the following error(s) on my terminal/logs...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide details about your environment.
      value: |
        - Target deployment platforms: [e.g. AWS/GCP/local cluster/etc...]
        - Target OSs: [e.g. RHEL 9/Ubuntu 24.04/etc...]
        - Host OS (where you are running Ansible from): [e.g. RHEL 9/Ubuntu 24.04/etc...]
        - Version of the NGINX Ansible role (or specific commit): [e.g. 0.25.0/commit hash]
        - Version of Ansible: [e.g. 2.16.5]
        - How is Ansible being managed: [e.g. CLI/pipeline/Automation Hub/etc...]
        - Version of Jinja2 (if you are using any templating capability): [e.g. 3.1.1]
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Feel free to add any other context/information/screenshots/etc... that you think might be relevant to this issue in here.
