---
name: ✨ Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Before you continue filling out this request, please take a moment to check that your feature has not been [already requested on GitHub][issue search] 🙌

        **Note:** If you are seeking community support or have a question, please consider starting a new thread via [GitHub discussions][discussions] or the [NGINX Community forum][forum].

        [issue search]: https://github.com/nginxinc/ansible-role-nginx/issues
        [discussions]: https://github.com/nginxinc/ansible-role-nginx/discussions
        [forum]: https://community.nginx.org

  - type: textarea
    id: overview
    attributes:
      label: Feature Overview
      description: A clear and concise description of what the feature request is.
      placeholder: I would like the NGINX Ansible role to be able to do "X".
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Detail any potential alternative solutions/workarounds you've used or considered.
      placeholder: I have done/might be able to do "X" in the NGINX Ansible role by doing "Y".

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Feel free to add any other context/information/screenshots/etc... that you think might be relevant to this feature request here.
